# Generated by Django 5.2.12 on 2026-04-02 14:25

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('needs_registration_code', models.TextField(unique=True)),
                ('title', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount_needed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('donors', models.JSONField(blank=True, default=list, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('partially_funded', 'Partially Funded'), ('fulfilled', 'Fulfilled'), ('expired', 'Expired'), ('closed', 'Closed')], default='pending', max_length=30)),
                ('expiring_at', models.DateTimeField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('need_type', models.CharField(choices=[('cash', 'Cash'), ('in_kind', 'In Kind')], default='in_kind', max_length=20)),
                ('unit', models.TextField(default='units')),
            ],
            options={
                'db_table': 'needs',
                'managed': False,
            },
        ),
    ]
