# Generated by Django 5.2.12 on 2026-04-02 14:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserManagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(editable=False, max_length=220)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('profile_photo', models.TextField(blank=True, null=True)),
                ('reg_code', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('donor', 'Donor'), ('volunteer', 'Volunteer')], default='donor', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('terminated', 'Terminated')], default='paused', max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('current_session_key', models.CharField(blank=True, max_length=255, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('sign_in_count', models.IntegerField(default=0)),
                ('forgot_password_change_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_management',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
