# Generated by Django 5.2.12 on 2026-04-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='reg_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='stock_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
